export default [
  'Speed limit (20kmph)',
  'Speed limit (30kmph)',
  'Speed limit (50kmph)',
  'Speed limit (60kmph)',
  'Speed limit (70kmph)',
  'Speed limit (80kmph)',
  'End of speed limit (80kmph)',
  'Speed limit (100kmph)',
  'Speed limit (120kmph)',
  'No passing',
  'No passing for vehicles over 3.5 metric tons',
  'Right-of-way at the next intersection',
  'Priority road',
  'Yield',
  'Stop',
  'No vehicles',
  'Vehicles over 3.5 metric tons prohibited',
  'No entry',
  'General caution',
  'Dangerous curve to the left',
  'Dangerous curve to the right',
  'Double curve',
  'Bumpy road',
  'Slippery road',
  'Road narrows on the right',
  'Road work',
  'Traffic signals',
  'Pedestrians',
  'Children crossing',
  'Bicycles crossing',
  'Beware of icesnow',
  'Wild animals crossing',
  'End of all speed and passing limits',
  'Turn right ahead',
  'Turn left ahead',
  'Ahead only',
  'Go straight or right',
  'Go straight or left',
  'Keep right',
  'Keep left',
  'Roundabout mandatory',
  'End of no passing',
  'End of no passing by vehicles over 3.5 metric tons',
];